menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'PI', url: '/pi'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Onur Serçinoğlu', title: 'Principal Investigator', department: 'Bioengineering', institution: 'Gebze Technical University', 
  institution_address: 'Gebze Technical University, Gebze, Kocaeli, Türkiye', phone: '(000) 000-0000', 
  email: 'osercinoglu@gtu.edu.tr', office: 'BYM110', image: 'assets/img/onur-sercinoglu.jpg', url: 'onur-sercinoglu'}
- {name: 'İlayda Erdoğan', title: 'Msc Student', department: 'Bioengineering', 
  institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', 
  email: 'i.erdogan2021@gtu.edu.tr', office: 'BYM010', image: 'assets/img/ilayda-erdogan.jpg', url: 'ilayda-erdogan'}
- {name: 'Şuara Şahin', title: 'Msc Student', department: 'Bioengineering', 
  institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', 
  email: 's.sahin2022@gtu.edu.tr', office: 'BYM010', image: 'assets/img/suara-sahin.jpg', url: 'suara-sahin'}
- {name: 'Tuba Okur', title: 'Research Assistant and Msc Student', department: 'Bioengineering', 
  institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', 
  email: 'tubaokur@gtu.edu.tr', office: 'BYM010', image: 'assets/img/suara-sahin.jpg', url: 'tuba-okur'}
- {name: 'Evren Atak', title: 'Msc Student', department: 'Bioengineering', 
  institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', 
  email: 'e.atak2022@gtu.edu.tr', office: '', image: 'assets/img/evren-atak.jpg', url: 'evren-atak'}
- {name: 'Alperen Tanrıkulu', title: 'Msc Student', department: 'Bioengineering', 
  institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', 
  email: 'a.tanrikulu2023@gtu.edu.tr', office: '', image: 'assets/img/alperen-tanrıkulu.jpg', url: 'alperen-tanrikulu'}
- {name: 'B. Olida Reisoğlu', title: 'Msc Student', department: 'Bioengineering', 
  institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', 
  email: 'b.reisoglu2023@gtu.edu.tr', office: '', image: 'assets/img/alperen-tanrıkulu.jpg', url: 'olida-reisoglu'}
- {name: 'Emre Taha Çevik', title: 'Bsc Student - Graduation Project', department: 'Bioengineering', 
  institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', 
  email: 'e.cevik2019@gtu.edu.tr', office: '', image: 'assets/img/emre-taha-cevik.jpg', url: 'emre-cevik'}

alumni:
- {name: 'Esra Büşra Işık', title: 'MSc Student', department: 'Bioengineering',
  department: 'Bioengineering', institution: 'Gebze Technical University', 
  institution_address: 'Gebze Technical University, Bioengineering Department, Gebze, Kocaeli, Türkiye', phone: '(000) 000-0000',
  email: "e.isik2020@gtu.edu.tr", office: 'Bioengineering Building BYM010', image: 'assets/img/esra-busra-isik.jpg', url: 'esra-busra-isik'}
- {name: 'Ayşe Sıla Kantarçeken', title: 'Internship',
  department: 'Genetics and Bioengineering', institution: 'Izmir University of Economics', 
  institution_address: '', phone: '(000) 000-0000',
  email: "", office: '', image: '', url: ''}

courses:
- {name: 'Bioengineering Fundamentals', url: 'https://bsb511.github.io'}
- {name: 'Computational Biomolecular Dynamics', url: 'computational-biomolecular-dynamics'}

social:
- {icon: 'github', link: 'https://github.com/costbio'}
- {icon: 'twitter', link: 'https://twitter.com/onursercin'}

contacts:
- {name: 'Dr. Onur', title: 'Assistant Professor', 
  department: 'Bioengineering', institution: 'Gebze Technical University', 
  institution_address: 'Gebze Technical University, Bioengineering Department, Gebze, Kocaeli, Türkiye', phone: '(000) 000-0000', email: 'osercinoglu@gtu.edu.tr', office: 'Bioengineering Building BYM010', image: 'assets/img/contact.jpg'}
