menu:
- {name: 'people', url: '/people', icon: 'boat'}
- {name: 'publications', url: '/publications', icon: 'books'}
- {name: 'tools', url: '/tools', icon: 'bow'}
- {name: 'PI', url: '/pi', icon: 'viking-helmet'}
- {name: 'contact', url: '/contact', icon: 'horn'}

people_personnel:
- {name: 'Onur Serçinoğlu', title: 'Principal Investigator', department: 'Bioengineering', institution: 'Gebze Technical University', 
  institution_address: 'Gebze Technical University, Gebze, Kocaeli, Türkiye', 
  email: 'osercinoglu A T gtu.edu.tr', office: 'BYM110',  url: 'onur-sercinoglu',
  linkedin: 'onursercinoglu'}

- {name: 'Tuğba Emine Eke', title: 'Research Assistant and Msc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '', 
  email: 'e.tugba A T gtu.edu.tr', office: 'BYM010', url: 'tugba-emine-eke'}

people_graduate:
- {name: 'Şevval Dik', title: 'PhD Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '', 
  email: 'sevvaldik A T gtu.edu.tr', url: 'sevval-dik'}

- {name: 'Hatice Nur Aydın', title: 'PhD Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '', 
  email: 'haydin2025 A T gtu.edu.tr', url: 'hatice-nur-aydin'}

- {name: 'Şuara Şahin', title: 'Msc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '', 
  email: 's.sahin2022 A T gtu.edu.tr', url: 'suara-sahin'}

- {name: 'Seher Burcu Özkan', title: 'Msc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '', 
  email: 's.ozkan2025 A T gtu.edu.tr', url: 'seher-burcu-ozkan'}

- {name: 'Emre Taha Çevik', title: 'Msc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '',  
  email: 'e.cevik2019 A T gtu.edu.tr', url: 'emre-cevik'}

- {name: 'Öyküm Önel', title: 'Msc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '',  
  email: 'o.onel2019 A T gtu.edu.tr', url: 'oykum-onel'}

- {name: 'Alper Tanrıkulu', title: 'Msc Student', department: 'Bioengineering',  program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '', 
  email: 'a.tanrikulu2023 A T gtu.edu.tr', url: 'alperen-tanrikulu'}

people_undergraduate:

people_alumni:
- {name: 'Tuba Okur', title: 'Research Assistant and Msc Student', department: 'Bioengineering',  program: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: 'tubaokur A T gtu.edu.tr', url: 'tuba-okur', current_position: ''}

- {name: 'Evren Atak', title: 'Msc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University', institution_address: '',
  email: 'e.atak2022 A T gtu.edu.tr', url: 'evren-atak', current_position: ''}

- {name: 'Zeynep Özer', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: 'z.ozer2019 A T gtu.edu.tr', url: 'zeynep-ozer', current_position: ''}

- {name: 'Gülçin Deniz Yavuz', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'gulcin-deniz-yavuz', current_position: ''}

- {name: 'Ayça Emanetoğlu', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'ayca-emanetoglu', current_position: ''}

- {name: 'Özge Timür', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'ozge-timur', current_position: ''}

- {name: 'Edanur Çatalca', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'edanur-catalca', current_position: ''}

- {name: 'Şevval Öztürk', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'sevval-ozturk', current_position: ''}

- {name: 'Ali Batuhan Çifer', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'ali-batuhan-cifer', current_position: ''}

- {name: 'Zehra İlayda Özdemir', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'zehra-ilayda-ozdemir', current_position: ''}

- {name: 'Begüm Topaloğlu', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'begum-topaloglu', current_position: ''}

- {name: 'Selin Tunçarslan', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: '', url: 'selin-tuncarslan', current_position: ''}

- {name: 'Esra Büşra Işık', title: 'MSc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University',
  institution_address: 'Gebze Technical University, Bioengineering Department, Gebze, Kocaeli, Türkiye',
  email: "e.isik2020 A T gtu.edu.tr", url: 'esra-busra-isik', current_position: ''}

- {name: 'İlayda Erdoğan', title: 'MSc Student', department: 'Bioengineering', program: 'Bioinformatics and Systems Biology',
  institution: 'Gebze Technical University',
  institution_address: 'Gebze Technical University, Bioengineering Department, Gebze, Kocaeli, Türkiye',
  email: "i.erdogan2021 A T gtu.edu.tr", url: 'ilayda-erdogan', current_position: ''}

- {name: 'Beyza Kurtoğlu', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: 'b.kurtoglu2019 A T gtu.edu.tr',  url: 'beyza-kurtoglu', current_position: ''}

- {name: 'Elif Bengü Kızılay', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: ' A T gtu.edu.tr',  url: 'elif-bengu-kizilay', current_position: ''}

- {name: 'Muhammet Eren Uluğ', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: ' A T gtu.edu.tr',  url: 'eren-ulug', current_position: ''}

- {name: 'Ceylin Karatepe', title: 'Bsc Student (Graduation Project)', department: 'Bioengineering',
  institution: 'Gebze Technical University', institution_address: '',
  email: ' A T gtu.edu.tr',  url: 'ceylin-karatepe', current_position: ''}

- {name: 'Ayşe Sıla Kantarçeken', title: 'Internship Student',
  department: 'Genetics and Bioengineering', institution: 'Izmir University of Economics',
  institution_address: '',
  email: "", url: '', current_position: ''}

social:
- {icon: 'github', link: 'https://github.com/costbio'}
- {icon: 'twitter', link: 'https://twitter.com/onursercin'}

contacts:
- {name: 'Dr. Onur Serçinoğlu', title: 'Assistant Professor',
  department: 'Bioengineering', institution: 'Gebze Technical University',
  institution_address: 'Gebze Technical University, Bioengineering Department, Gebze, Kocaeli, Türkiye', email: 'osercinoglu A T gtu.edu.tr', office: 'Bioengineering Building BYM010'}
