menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Onur Serçinoğlu', title: 'Principal Investigator', department: 'Bioengineering', institution: 'Gebze Technical University', 
  institution_address: 'Gebze Technical University, Gebze, Kocaeli, Türkiye', phone: '(000) 000-0000', email: 'osercinoglu@gtu.edu.tr', office: 'BYM110', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'İlayda Erdoğan', title: 'Graduate Student', department: 'Bioengineering', institution: 'Gebze Technical University', institution_address: '', phone: '(000) 000-0000', email: 'ierdogan2021@gtu.edu.tr', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Bioengineering Fundamentals', url: 'https://bsb511.github.io'}
- {name: 'Computational Biomolecular Dynamics', url: 'computational-biomolecular-dynamics'}

social:
- {icon: 'github', link: 'https://github.com/costbio'}
- {icon: 'twitter', link: 'https://twitter.com/onursercin'}

contacts:
- {name: 'Dr. Onur', title: 'Assistant Professor', 
  department: 'Bioengineering', institution: 'Gebze Technical University', 
  institution_address: 'Gebze Technical University, Bioengineering Department, Gebze, Kocaeli, Türkiye', phone: '(000) 000-0000', email: 'osercinoglu@gtu.edu.tr', office: 'Bioengineering Building BYM010', image: 'assets/img/contact.jpg'}
